[mypy]
python_version = 3.11
ignore_missing_imports = True
exclude = (?x)(
    ^\.venv/
    | ^\.mypy_cache/
    | ^\.pytest_cache/
    | ^tests/
  )

[mypy-canvas_sdk.*]
ignore_missing_imports = True

[mypy-django.*]
ignore_missing_imports = True

[mypy-logger]
ignore_missing_imports = True

[mypy-clinical_pathways.models.*]
disable_error_code = var-annotated
