from __future__ import annotations

MAX_RESULTS = 50
ALL_CATEGORY_LIMIT = 8

COMMAND_TYPE_LABELS: dict[str, str] = {
    "adjustPrescription": "Adjust Prescription",
    "allergy": "Allergy",
    "approveRefill": "Approve Refill",
    "assess": "Assess Condition",
    "assessCodingGap": "Assess Coding Gap",
    "cancelPrescription": "Cancel Prescription",
    "changeMedication": "Change Medication",
    "chartSectionReview": "Chart Section Reviewed",
    "closeGoal": "Close Goal",
    "consultReportReview": "Consult Report Review",
    "createCodingGap": "Create Coding Gap",
    "deferCodingGap": "Defer Coding Gap",
    "denyRefill": "Deny Refill",
    "diagnose": "Diagnose",
    "educationalMaterial": "Educational Material",
    "exam": "Physical Exam",
    "familyHistory": "Family History",
    "followUp": "Follow Up",
    "goal": "Goal",
    "hpi": "History of Present Illness",
    "imagingOrder": "Imaging Order",
    "imagingReview": "Imaging Report Review",
    "immunizationStatement": "Immunization Statement",
    "immunize": "Immunize",
    "instruct": "Instruct",
    "labOrder": "Lab Order",
    "labReview": "Lab Review",
    "medicalDocumentReview": "Medical Document Review",
    "medicalHistory": "Medical History",
    "medicationStatement": "Medication Statement",
    "perform": "Perform",
    "plan": "Plan",
    "pocLabTest": "POC Lab Test",
    "prescribe": "Prescribe",
    "questionnaire": "Questionnaire",
    "reasonForVisit": "Reason for Visit",
    "refer": "Refer",
    "referralReview": "Referral Review",
    "refill": "Refill",
    "removeAllergy": "Remove Allergy",
    "resolveCondition": "Resolve Condition",
    "ros": "Review of Systems",
    "snoozeProtocol": "Snooze Protocol",
    "stopMedication": "Stop Medication",
    "structuredAssessment": "Structured Assessment",
    "surgicalHistory": "Surgical History",
    "task": "Task",
    "uncategorizedDocumentReview": "Document Review",
    "updateGoal": "Update Goal",
    "validateCodingGap": "Validate Coding Gap",
    "visualExamFinding": "Visual Exam Finding",
    "vitals": "Vitals",
}

COMMAND_ABBREVIATIONS: dict[str, set[str]] = {
    "hpi": {"hpi"},
    "rfv": {"reasonForVisit"},
    "ros": {"ros"},
    "pe": {"exam"},
    "exam": {"exam"},
    "fhx": {"familyHistory"},
    "pmh": {"medicalHistory"},
    "dx": {"diagnose"},
    "rx": {"prescribe"},
    "fu": {"followUp"},
    "img": {"imagingOrder"},
    "lab": {"labOrder"},
    "ref": {"refer"},
    "edu": {"educationalMaterial"},
    "imm": {"immunize"},
    "mx": {"medicationStatement"},
}

_LABEL_TO_KEYS: dict[str, set[str]] = {}
for _sk, _label in COMMAND_TYPE_LABELS.items():
    _LABEL_TO_KEYS.setdefault(_label.lower(), set()).add(_sk)

SKIP_DATA_KEYS = frozenset(
    {
        "id",
        "uuid",
        "dbid",
        "pk",
        "created",
        "modified",
        "deleted",
        "state",
        "schema_key",
        "schema_version",
        "command_uuid",
        "note_id",
        "patient_id",
        "originator_id",
        "committer_id",
        "entered_in_error",
        "version",
        "source",
        "representative_ndc",
        "erx_ncpdp_script_quantity_qualifier_code",
        "clinical_quantities",
    }
)

_MED_COMMAND_KEYS = frozenset({
    "prescribe",
    "refill",
    "stopMedication",
    "medicationStatement",
    "adjustPrescription",
    "approveRefill",
    "denyRefill",
})

_PRESCRIPTION_STATUS_MAP: dict[str, tuple[str, str]] = {
    "ultimately-accepted": ("Accepted", "completed"),
    "delivered": ("Delivered", "completed"),
    "signed": ("Signed", "completed"),
    "pending": ("Pending", "pending"),
    "received": ("Received", "pending"),
    "inqueue": ("In Queue", "pending"),
    "transmitted": ("Transmitted", "pending"),
    "open": ("Open", "uncommitted"),
    "error": ("Error", "cancelled"),
    "canceled": ("Cancelled", "cancelled"),
    "cancel-requested": ("Cancel Requested", "pending"),
    "cancel-denied": ("Cancel Denied", "cancelled"),
}

_HEADING_KEY: dict[str, str] = {
    "adjustPrescription": "prescribe",
    "allergy": "allergy",
    "approveRefill": "prescribe",
    "assess": "condition",
    "assessCodingGap": "diagnose",
    "cancelPrescription": "prescribe",
    "changeMedication": "medication",
    "closeGoal": "goal_statement",
    "consultReportReview": "report",
    "createCodingGap": "diagnose",
    "deferCodingGap": "detected_issue",
    "denyRefill": "prescribe",
    "diagnose": "diagnose",
    "educationalMaterial": "title",
    "familyHistory": "family_history",
    "followUp": "coding",
    "goal": "goal_statement",
    "imagingOrder": "image",
    "imagingReview": "report",
    "immunizationStatement": "statement",
    "immunize": "coding",
    "instruct": "instruct",
    "labReview": "report",
    "medicalDocumentReview": "report",
    "medicalHistory": "past_medical_history",
    "medicationStatement": "medication",
    "perform": "perform",
    "pocLabTest": "coding",
    "prescribe": "prescribe",
    "questionnaire": "questionnaire",
    "reasonForVisit": "coding",
    "referralReview": "report",
    "refer": "refer_to",
    "refill": "prescribe",
    "removeAllergy": "allergy",
    "resolveCondition": "condition",
    "snoozeProtocol": "protocol",
    "stopMedication": "medication",
    "structuredAssessment": "questionnaire",
    "surgicalHistory": "past_surgical_history",
    "uncategorizedDocumentReview": "report",
    "updateGoal": "goal_statement",
    "validateCodingGap": "detected_issue",
}

_DETAIL_FIELDS: dict[str, list[tuple[str, str]]] = {
    "adjustPrescription": [
        ("prescribe", "Medication"),
        ("changed_to", "Changed to"),
        ("sig", "Sig"),
        ("days_supply", "Days supply"),
        ("$qty", "Quantity to dispense"),
        ("refills", "Refills"),
        ("substitutions", "Substitutions"),
        ("pharmacy", "Pharmacy"),
        ("prescriber", "Prescriber"),
        ("supervising_provider", "Supervising provider"),
        ("note_to_pharmacist", "Note to pharmacist"),
    ],
    "allergy": [
        ("allergy", "Allergen"),
        ("severity", "Severity"),
        ("narrative", "Reaction"),
        ("approximate_date", "Approx. date"),
    ],
    "approveRefill": [
        ("prescribe", "Medication"),
        ("total_quantity", "Total quantity"),
        ("directions", "Directions"),
        ("pharmacy", "Pharmacy"),
        ("total_dispensings_approved", "Total dispensings approved"),
    ],
    "assess": [
        ("condition", "Condition"),
        ("background", "Background"),
        ("status", "Status"),
        ("narrative", "Assessment"),
    ],
    "assessCodingGap": [
        ("diagnose", "Condition"),
        ("status", "Status"),
        ("details", "Note"),
        ("approximate_date_of_onset", "Onset date"),
        ("todays_assessment", "Assessment"),
    ],
    "cancelPrescription": [
        ("prescribe", "Medication"),
        ("stop_medication", "Stop medication"),
        ("rationale", "Rationale"),
    ],
    "changeMedication": [
        ("medication", "Medication"),
        ("sig", "Sig"),
    ],
    "chartSectionReview": [
        ("section", "Section"),
    ],
    "closeGoal": [
        ("goal_statement", "Goal"),
        ("achievement_status", "Status"),
        ("progress", "Progress"),
    ],
    "consultReportReview": [
        ("report", "Report"),
        ("message_to_patient", "Patient message"),
        ("communication_method", "Communication method"),
        ("internal_comment", "Internal comment"),
    ],
    "createCodingGap": [
        ("diagnose", "Condition"),
        ("status", "Status"),
        ("date", "Date"),
        ("details", "Note"),
    ],
    "deferCodingGap": [
        ("detected_issue", "Detected issue"),
    ],
    "denyRefill": [
        ("prescribe", "Medication"),
        ("reason", "Reason"),
        ("total_quantity", "Total quantity"),
        ("directions", "Directions"),
        ("pharmacy", "Pharmacy"),
    ],
    "diagnose": [
        ("diagnose", "Diagnosis"),
        ("background", "Background"),
        ("approximate_date_of_onset", "Approx. onset date"),
        ("today_assessment", "Assessment"),
    ],
    "educationalMaterial": [
        ("title", "Title"),
    ],
    "familyHistory": [
        ("family_history", "Condition"),
        ("relative", "Relative"),
        ("note", "Note"),
    ],
    "followUp": [
        ("coding", "Reason for visit"),
        ("note_type", "Visit type"),
        ("requested_date", "Requested date"),
        ("comment", "Scheduling comment"),
    ],
    "goal": [
        ("goal_statement", "Goal"),
        ("start_date", "Start date"),
        ("due_date", "Due date"),
        ("achievement_status", "Status"),
        ("priority", "Priority"),
        ("progress", "Progress/barriers"),
    ],
    "hpi": [
        ("narrative", "Narrative"),
    ],
    "imagingOrder": [
        ("image", "Image"),
        ("indications", "Indications"),
        ("priority", "Priority"),
        ("additional_details", "Additional details"),
        ("imaging_center", "Imaging center"),
        ("ordering_provider", "Ordering provider"),
        ("internal_comment", "Internal comment"),
    ],
    "imagingReview": [
        ("report", "Report"),
        ("message_to_patient", "Patient message"),
        ("communication_method", "Communication method"),
        ("internal_comment", "Internal comment"),
    ],
    "immunize": [
        ("coding", "Vaccine"),
        ("lot_number", "Lot number"),
        ("manufacturer", "Manufacturer"),
        ("exp_date_original", "Expiration date"),
        ("sig_original", "Sig"),
        ("given_by", "Given by"),
    ],
    "immunizationStatement": [
        ("statement", "Immunization"),
        ("date", "Approx. date"),
        ("comments", "Comment"),
    ],
    "instruct": [
        ("instruct", "Instruction"),
        ("narrative", "Comment"),
    ],
    "labOrder": [
        ("tests", "Tests"),
        ("lab_partner", "Lab partner"),
        ("ordering_provider", "Ordering provider"),
        ("diagnosis", "Indications"),
        ("fasting_status", "Fasting status"),
        ("comment", "Comment"),
    ],
    "labReview": [
        ("report", "Report"),
        ("message_to_patient", "Patient message"),
        ("communication_method", "Communication method"),
        ("internal_comment", "Internal comment"),
    ],
    "medicalDocumentReview": [
        ("report", "Report"),
        ("message_to_patient", "Patient message"),
        ("communication_method", "Communication method"),
        ("internal_comment", "Internal comment"),
    ],
    "medicalHistory": [
        ("past_medical_history", "Condition"),
        ("approximate_start_date", "Approx. start"),
        ("approximate_end_date", "Approx. end"),
        ("comments", "Comments"),
    ],
    "medicationStatement": [
        ("medication", "Medication"),
        ("sig", "Sig"),
    ],
    "perform": [
        ("perform", "Procedure"),
        ("notes", "Notes"),
    ],
    "plan": [
        ("narrative", "Narrative"),
    ],
    "pocLabTest": [
        ("coding", "Lab test"),
        ("indications", "Indications"),
        ("comment", "Comment"),
    ],
    "prescribe": [
        ("prescribe", "Medication"),
        ("indications", "Indications"),
        ("sig", "Sig"),
        ("days_supply", "Days supply"),
        ("$qty", "Quantity to dispense"),
        ("refills", "Refills"),
        ("substitutions", "Substitutions"),
        ("pharmacy", "Pharmacy"),
        ("prescriber", "Prescriber"),
        ("supervising_provider", "Supervising provider"),
        ("note_to_pharmacist", "Note to pharmacist"),
    ],
    "reasonForVisit": [
        ("coding", "Reason"),
        ("comment", "Comment"),
    ],
    "refer": [
        ("refer_to", "Refer to"),
        ("indications", "Indications"),
        ("clinical_question", "Clinical question"),
        ("priority", "Priority"),
        ("notes_to_specialist", "Notes to specialist"),
        ("internal_comment", "Internal comment"),
    ],
    "referralReview": [
        ("report", "Report"),
        ("message_to_patient", "Patient message"),
        ("communication_method", "Communication method"),
        ("internal_comment", "Internal comment"),
    ],
    "refill": [
        ("prescribe", "Medication"),
        ("indications", "Indications"),
        ("sig", "Sig"),
        ("days_supply", "Days supply"),
        ("$qty", "Quantity to dispense"),
        ("refills", "Refills"),
        ("substitutions", "Substitutions"),
        ("pharmacy", "Pharmacy"),
        ("prescriber", "Prescriber"),
        ("supervising_provider", "Supervising provider"),
        ("note_to_pharmacist", "Note to pharmacist"),
    ],
    "removeAllergy": [
        ("allergy", "Allergen"),
        ("narrative", "Rationale"),
    ],
    "resolveCondition": [
        ("condition", "Condition"),
        ("rationale", "Rationale"),
    ],
    "snoozeProtocol": [
        ("protocol", "Protocol"),
        ("snooze_until_date", "Snooze until"),
        ("snooze_reason", "Reason"),
        ("snooze_comment", "Comment"),
    ],
    "stopMedication": [
        ("medication", "Medication"),
        ("rationale", "Rationale"),
    ],
    "surgicalHistory": [
        ("past_surgical_history", "Procedure"),
        ("approximate_date", "Approx. date"),
        ("comment", "Comments"),
    ],
    "task": [
        ("title", "Title"),
        ("assign_to", "Assigned to"),
        ("due_date", "Due date"),
        ("comment", "Comment"),
        ("labels", "Labels"),
    ],
    "uncategorizedDocumentReview": [
        ("report", "Report"),
        ("message_to_patient", "Patient message"),
        ("communication_method", "Communication method"),
        ("internal_comment", "Internal comment"),
    ],
    "updateGoal": [
        ("goal_statement", "Goal"),
        ("due_date", "Due date"),
        ("achievement_status", "Status"),
        ("priority", "Priority"),
        ("progress", "Progress/barriers"),
    ],
    "validateCodingGap": [
        ("detected_issue", "Detected issue"),
        ("status", "Status"),
        ("date", "Date"),
        ("details", "Note"),
    ],
    "visualExamFinding": [
        ("comment", "Comment"),
    ],
    "vitals": [
        ("height", "Height"),
        ("weight_lbs", "Weight (lbs)"),
        ("weight_oz", "Weight (oz)"),
        ("waist_circumference", "Waist circumference"),
        ("body_temperature", "Temperature"),
        ("body_temperature_site", "Temperature site"),
        ("blood_pressure_systole", "Blood pressure systolic"),
        ("blood_pressure_diastole", "Blood pressure diastolic"),
        ("blood_pressure_position_and_site", "Blood pressure position/site"),
        ("pulse", "Pulse"),
        ("pulse_rhythm", "Pulse rhythm"),
        ("respiration_rate", "Respiration rate"),
        ("oxygen_saturation", "Oxygen saturation"),
        ("note", "Notes"),
    ],
}

_MAX_HEADING_LEN = 150

_CODE_IN_HEADING = {
    "diagnose", "deferCodingGap", "validateCodingGap", "assessCodingGap",
    "createCodingGap", "resolveCondition", "familyHistory", "medicalHistory",
    "surgicalHistory", "immunize", "immunizationStatement", "imagingOrder",
    "perform", "pocLabTest",
}

