[tool.poetry]
name = "data-migrations"
version = "0.1.0"
description = ""
authors = ["Reba Magier <reba.magier@canvasmedical.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
