"""The handler serves the React bundle from the generated _assets module."""

from base64 import b64decode

from scheduling_app._assets import ASSETS, BUILT
from scheduling_app.handlers.scheduling_web_app import (
    CONTENT_TYPES,
    NOT_BUILT_HTML,
    SchedulingWebApp,
)


def test_bundle_is_built() -> None:
    """The committed bundle (generated by `yarn build`) is present for installed plugins."""
    assert BUILT is True
    # Vite emits fixed, unhashed names so the single-segment asset route can serve them.
    assert {"index.html", "app.js", "index.css"} <= set(ASSETS)


def test_embedded_assets_are_valid_base64() -> None:
    """Each embedded asset decodes to bytes (served raw, bypassing the template engine)."""
    for name, encoded in ASSETS.items():
        assert b64decode(encoded), f"{name} decoded to empty bytes"


def test_handler_serving_constants() -> None:
    """The handler imports cleanly and exposes the asset-serving constants."""
    assert SchedulingWebApp.PREFIX == "/app"
    assert CONTENT_TYPES["js"] == "text/javascript"
    assert CONTENT_TYPES["html"].startswith("text/html")
    assert "not built" in NOT_BUILT_HTML.lower()
