// Post-build step: read everything Vite emitted into ./dist, base64-encode it,
// and write ../../scheduling_app/_assets.py. The plugin serves these
// bytes raw (Response(b64decode(...))) because the sandbox blocks file I/O and
// render_to_string would corrupt a minified bundle containing {{ / {%.
// Vite is configured with assetsDir "." so files (index.html, app.js, app.css)
// sit at the dist root and line up with the `/app/assets/<filename>` route.

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const distDir = path.resolve(here, "../dist");
const outFile = path.resolve(here, "../../scheduling_app/_assets.py");

function collect(dir, prefix = "") {
  const out = {};
  for (const name of readdirSync(dir)) {
    const full = path.join(dir, name);
    const rel = prefix ? `${prefix}/${name}` : name;
    if (statSync(full).isDirectory()) Object.assign(out, collect(full, rel));
    else out[rel] = readFileSync(full).toString("base64");
  }
  return out;
}

const assets = collect(distDir);

const lines = [
  "# AUTO-GENERATED by frontend/scripts/embed-assets.mjs — do not edit by hand.",
  "#",
  "# Base64-encoded built frontend assets, served as raw bytes by",
  "# handlers/scheduling_web_app.py. Stored as a Python module because the plugin",
  "# sandbox blocks file I/O, and served raw (not via render_to_string) because",
  "# Django's template engine would corrupt a minified bundle containing {{ / {%.",
  "#",
  "# Run `yarn build` in ./frontend to regenerate this file.",
  "",
  "ASSETS = {",
  ...Object.entries(assets).map(
    ([name, b64]) => `    ${JSON.stringify(name)}: ${JSON.stringify(b64)},`,
  ),
  "}",
  "BUILT = True",
  "",
];

writeFileSync(outFile, lines.join("\n"));
console.log(`Embedded ${Object.keys(assets).length} asset(s) -> ${outFile}`);
