name: Update Coding Agent Context

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9am UTC
  workflow_dispatch:  # Allows manual trigger from Actions tab

jobs:
  update-context:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Run update script
        run: uv run assemble_coding_agent_context.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add coding_agent_context.txt
          git diff --staged --quiet || git commit -m "Update coding agent context [automated]"
          git push
